name: Cross-compile

on:
  push:
    tags:
      - 'v*'

jobs:
  cross-compile:
    name: Cross-compile for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-musl

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross
      run: cargo install cross

    - name: Build target
      run: cross build --release --target ${{ matrix.target }}

    - name: Prepare asset
      run: |
        cd target/${{ matrix.target }}/release
        tar czf ../../../dct-${{ matrix.target }}.tar.gz dct*

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dct-${{ matrix.target }}
        path: dct-${{ matrix.target }}.tar.gz